# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelActivities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
