# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelActivities', '0002_auto_20170301_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(choices=[('0', 'Ground Floor'), ('1', '1st Floor'), ('2', '2nd Floor'), ('3', '3rd Floor'), ('4', '4th Floor')], default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_size',
            field=models.CharField(choices=[('1', 'Single Seater'), ('2', 'Double Seater'), ('3', 'Triple Seater')], default='1', max_length=15),
        ),
    ]
