# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HostelActivities', '0003_auto_20170301_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='allocated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.User'),
        ),
    ]
