# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-15 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HostelActivities', '0004_auto_20170301_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notices',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notices',
            name='notices',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
