# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-26 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
