# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20170226_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobileno',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
