# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20170228_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobileno',
            new_name='college',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
