# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20170301_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_size', models.CharField(choices=[('1', 'Single Seater'), ('2', 'Double Seater'), ('3', 'Triple Seater')], default='1', max_length=15)),
                ('room_type', models.CharField(choices=[('NON-AC', 'NON-AC'), ('AC', 'AC')], default='NON_AC', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
