# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('userprofile', '0008_auto_20170401_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('display_name', models.CharField(blank=True, default='', max_length=254, verbose_name='display name')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            bases=('auth.group',),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='account_user_set', to='userprofile.OurGroup', verbose_name='account groups'),
        ),
    ]
